package com.qa.skyrim.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import com.qa.skyrim.entity.Post;



public interface PostRepo extends JpaRepository<Post, Integer>{

	// custom query method, implementation auto generated by Spring. Will be looked at later...
	List<Post> findByUserId(int id);
}
